name: test

on:
  release:
    types: [published]  # Trigger only when a release is published

permissions:
  contents: read

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for PyPI Trusted Publishing

    environment:
      name: pypi  # Optional: use GitHub Environments for safety

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build tool
        run: |
          python -m pip install --upgrade pip build

      - name: Build distributions
        run: |
          python -m build  # Creates dist/*.whl and dist/*.tar.gz

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1